### ISSUE TITLE
artic tools get_scheme error (conversion of data to type "j" failed)

### ISSUE THREAD

**Issue by aholderb** [artic-network/primer-schemes#13]
Hi!

I've tried to download the latest ARTIC primer scheme for SARS-COV-2 with the following command: artic-tools get_scheme nCoV-2019

This gives the following result:

[11:18:27] [artic-tools::get_scheme] starting primer scheme downloader
[11:18:27] [artic-tools::get_scheme] requested scheme: nCoV-2019
[11:18:27] [artic-tools::get_scheme] requested version: latest
[11:18:27] [artic-tools::get_scheme] fetching manifest file
[11:18:27] [artic-tools::get_scheme] ARTIC manifest URL: https://raw.githubusercontent.com/artic-network/primer-schemes/master/schemes_manifest.json
[11:18:27] [artic-tools::get_scheme] ARTIC repository DOI: 10.5281/zenodo.4004423
[11:18:27] [artic-tools::get_scheme] finding primer scheme
[11:18:27] [artic-tools::get_scheme] found requested scheme: sars-cov-2 (using alias nCoV-2019)
error--> conversion of data to type "j" failed

I am new to linux and the command line and I do not really understand what is going wrong. Am I missing some software to convert the data? 

If somebody could shed a light on this error, many thanks!

**Comment by BioWilko** [comment]
I'm sorry for the extremely late reply but this is down to the change to minor versioning `V4.1` which means that the scheme version can no longer be represented by an integer which breaks artic_tools since it is written in C++. In the fieldbioinformatics pipeline I have re-written the functionality of get_scheme into the pipeline itself so it is no longer used https://github.com/artic-network/fieldbioinformatics/blob/a30c6e596449134556aafbcaceca8f51408c98d1/artic/minion.py#L44 which you can find there if useful.

**Comment by CGB858** [comment]
Hi, 
I was having the same issue as above; I am also very new to command line so don’t really understand what I am doing yet. 
I tried looking at the link BioWilko posted but I am confused about what information to input to download the primer schemes. 

I assumed I should input this line: 
get_scheme(scheme_name, scheme_directory, scheme_version="1")

However, I was unsure what should be inputted as the scheme name and directory, I tried “nCoV-2019” ,“ARTIC”, “PrimerScheme” for the name and tried the same for the directory as well as trying to use the URL but it keeps saying there was a syntax error. 

If possible, would anyone be able to provide an example of how you would write this in command line to download the V4.1 primer scheme? Or shed a light on something I am probably doing wrong?

Many thanks in advance!

**Comment by aholderb** [comment]
Many thanks @BioWilko for the reply.

@CGB858: I ended up manually downloading the primer scheme from https://github.com/artic-network/artic-ncov2019/tree/master/primer_schemes/nCoV-2019/V4.1. Just copy everything into separate .txt files and change the name and the extention of the file into the mentioned one. 

Then put all the files into a new directory in the location where the artic protocol searches the scheme (in the command after "--scheme-directory").

Finally, in the "artic minion --normalise 200 --threads 4 --scheme-directory ~/artic-ncov2019/primer_schemes --read-file run_name_barcode03.fastq --fast5-directory path_to_fast5 --sequencing-summary path_to_sequencing_summary.txt nCoV-2019/V3 samplename" command, change the "V3" from "nCoV-2019/V3" to the name of the new directory.

**Comment by CGB858** [comment]
Hi @aholderb thank you for your quick response, 

I had already tried downloading manually but for some reason when running the script I still get the error 
‘could not find primer scheme and reference sequence, attempting to download’

Which obviously then fails. I have tried downloading the files separately and all together in a zip file but that makes no difference .

This is why I was hoping to download it using the ‘get_scheme’ command somehow but no luck.
