### ISSUE TITLE
SARS-CoV-2: C44T seems to be common to all BA.2/4/5 but overlap primer 1 LEFT

### ISSUE THREAD

**Issue by corneliusroemer** [artic-network/primer-schemes#16]
It appears that nuc:C44T is common to all BA.2/4/5 (at least) but only called in ~40% of cases because it overlaps ARTIC primer 1 LEFT (at least v4.1, but probably most other versions too).

I'm not sure whether anything can be done about this, but if there is it would be nice to address this.

C44T went up exactly when BA.2 first appeared and is also seen in BA.4/5

Since BA.2/4/5 descendants make up ~99% of current circulation it's not unreasonable to assume that 44T has fixed.

Maybe the right way is to switch the primer base instead of changing the location then? It would in any case be nice if ARTIC users called 44T consistently in the future.

<img width="2543" alt="image" src="https://user-images.githubusercontent.com/25161793/199804181-8b9bbf55-2874-4ccf-be0c-465fd43bef78.png">

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=C44T&

**Comment by BioWilko** [comment]
There is nothing we can do to address this since it is the terminal primer in the scheme therefore not overlapped by any other amplicon, it is an unavoidable feature of primer scheme design unfortunately.
