### ISSUE TITLE
Position of SARS-CoV-2_64_LEFT does not yield sequence for SARS-CoV-2_64_LEFT

### ISSUE THREAD

**Issue by bioinformatikLabormedizinUSB** [artic-network/primer-schemes#17]
Dear Sir or Madam,

I noticed that in the Bed file(s), primer positions of SARS-CoV-2_64_LEFT is not correct.
It is defined by 19183 to 19222, however, correct is 19183 to 19208 (alternatively length and sequence is incorrect)

Cheers,
Pascal

**Comment by BioWilko** [comment]
This is intentional to filter out the following primer dimerisation product described here: https://virological.org/t/erroneous-mutations-associated-with-64-l-60-r-primer-dimer-in-artic-4-4-1/789
