### ISSUE TITLE
Getting fasta file for trimmomatic

### ISSUE THREAD

**Issue by lskatz** [artic-network/primer-schemes#8]
Is there a conventional way to get the fasta file for trimmomatic?  The fasta file that contains all primers for a given scheme.

I was trying this and it seems to work.

    bedtools getfasta -fi nCoV-2019.reference.fasta -fo nCoV-2019.primers.fasta -bed nCoV-2019.bed  -name

**Comment by will-rowe** [comment]
Heya @lskatz 

The primer seqs are found the 3rd column of the `*.tsv` in each primer scheme directory. But it looks like your one-liner does the job!

I've also got a subcommand in [artic-tools](https://github.com/will-rowe/artic-tools) which validates a scheme and outputs the multifasta of primer sequences. Requires the ref and bed file and all primer seqs are written in the same orientation.

```
artic-tools get_scheme scov2
artic-tools validate_scheme -o primerSeqs.fa -r scov2.v3.reference.fasta scov2.v3.primer.bed 
```
